food:
  cornflakes:
    - corn
    - cotton flakes
  pea soup:
    - soup
  pancake mix:
    - pancake
  hagelslag:
    - haggle
    - bagel
  sausages:
    - sausage
  mayonnaise:
    - mayo
    - majo

fruits:
  pear:
    - bear
  strawberry:
    - berry

snacks:
  stroopwafel:
    - wafel
    - stroop
    - troop
    - stroop off
    - strip off
  candy:
    - andy
  liquorice:
    - liquor
  crisps:
    - crisp
  pringles:
    - pringle
  tictac:
    - tic tac

drinks:
  cola:
    - coka
  ice tea:
    - tea
  fanta:
    - fun
    - funny
  ice tea:
    - nice tea
  dubbelfris:
    - double
    - double free
    - double three
    - double freeze

names:
  hayley:
    - hailey
    - haley
  emma:
    - hema
  sara:
    - sarah
  laura:
    - lore
  fleur:
    - flor
    - flower
    - flora
  gabrielle:
    - gabriel

food:
  strawberry jello:
    - strawberry giallo
    - strawberry yellow
  chocolate jello:
    - chocolate giallo
    - chocolate yellow
  coffee grounds:
    - coffee ground

toys:
  rubik's cube:
    - rubik's
    - rubik's tube
    - rubik's screw
    - rubiks cube
